INFO    : Since no target was supplied, we will use "web".

INFO    : Now preparing local server to preview your project directory `/home/innodems-intern2/Desktop/CBC-book/CBC-grade-9-pretext-book`.
INFO    :   (Reminder: use `pretext deploy` to deploy your built project to a public
INFO    :   GitHub Pages site that can be shared with readers who cannot access your
INFO    :   personal computer.)
INFO    : 
INFO    : starting server ...
INFO    : setting up ...
INFO    : values set...
INFO    : adding server entry
INFO    : There are 10 or more servers on file. Cleaning up ...
INFO    : Found entry no longer exists 5437
INFO    : Terminating 5437
INFO    : Terminate failed for 5437.
ERROR   : process PID not found (pid=5437)
Traceback (most recent call last):
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/pretext/server.py", line 76, in terminate
    psutil.Process(self.pid).terminate()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/psutil/__init__.py", line 317, in __init__
    self._init(pid)
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/psutil/__init__.py", line 363, in _init
    raise NoSuchProcess(pid, msg=msg) from None
psutil.NoSuchProcess: process PID not found (pid=5437)
INFO    : Found entry no longer exists 21686
INFO    : Terminating 21686
INFO    : Terminate failed for 21686.
ERROR   : process PID not found (pid=21686)
Traceback (most recent call last):
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/pretext/server.py", line 76, in terminate
    psutil.Process(self.pid).terminate()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/psutil/__init__.py", line 317, in __init__
    self._init(pid)
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/psutil/__init__.py", line 363, in _init
    raise NoSuchProcess(pid, msg=msg) from None
psutil.NoSuchProcess: process PID not found (pid=21686)
INFO    : Found entry no longer exists 31709
INFO    : Terminating 31709
INFO    : Terminate failed for 31709.
ERROR   : process PID not found (pid=31709)
Traceback (most recent call last):
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/pretext/server.py", line 76, in terminate
    psutil.Process(self.pid).terminate()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/psutil/__init__.py", line 317, in __init__
    self._init(pid)
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/psutil/__init__.py", line 363, in _init
    raise NoSuchProcess(pid, msg=msg) from None
psutil.NoSuchProcess: process PID not found (pid=31709)
INFO    : Found entry no longer exists 50903
INFO    : Terminating 50903
INFO    : Terminate failed for 50903.
ERROR   : process PID not found (pid=50903)
Traceback (most recent call last):
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/pretext/server.py", line 76, in terminate
    psutil.Process(self.pid).terminate()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/psutil/__init__.py", line 317, in __init__
    self._init(pid)
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/psutil/__init__.py", line 363, in _init
    raise NoSuchProcess(pid, msg=msg) from None
psutil.NoSuchProcess: process PID not found (pid=50903)
INFO    : Found entry no longer exists 66680
INFO    : Terminating 66680
INFO    : Terminate failed for 66680.
ERROR   : process PID not found (pid=66680)
Traceback (most recent call last):
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/pretext/server.py", line 76, in terminate
    psutil.Process(self.pid).terminate()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/psutil/__init__.py", line 317, in __init__
    self._init(pid)
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/psutil/__init__.py", line 363, in _init
    raise NoSuchProcess(pid, msg=msg) from None
psutil.NoSuchProcess: process PID not found (pid=66680)
INFO    : Found entry no longer exists 5490
INFO    : Terminating 5490
INFO    : Terminate failed for 5490.
ERROR   : process PID not found (pid=5490)
Traceback (most recent call last):
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/pretext/server.py", line 76, in terminate
    psutil.Process(self.pid).terminate()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/psutil/__init__.py", line 317, in __init__
    self._init(pid)
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/psutil/__init__.py", line 363, in _init
    raise NoSuchProcess(pid, msg=msg) from None
psutil.NoSuchProcess: process PID not found (pid=5490)
INFO    : Found entry no longer exists 9153
INFO    : Terminating 9153
INFO    : Terminate failed for 9153.
ERROR   : process PID not found (pid=9153)
Traceback (most recent call last):
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/pretext/server.py", line 76, in terminate
    psutil.Process(self.pid).terminate()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/psutil/__init__.py", line 317, in __init__
    self._init(pid)
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/psutil/__init__.py", line 363, in _init
    raise NoSuchProcess(pid, msg=msg) from None
psutil.NoSuchProcess: process PID not found (pid=9153)
INFO    : Found entry no longer exists 50521
INFO    : Terminating 50521
INFO    : Terminate failed for 50521.
ERROR   : process PID not found (pid=50521)
Traceback (most recent call last):
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/pretext/server.py", line 76, in terminate
    psutil.Process(self.pid).terminate()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/psutil/__init__.py", line 317, in __init__
    self._init(pid)
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/psutil/__init__.py", line 363, in _init
    raise NoSuchProcess(pid, msg=msg) from None
psutil.NoSuchProcess: process PID not found (pid=50521)
INFO    : Found entry no longer exists 39985
INFO    : Terminating 39985
INFO    : Terminate failed for 39985.
ERROR   : process PID not found (pid=39985)
Traceback (most recent call last):
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/pretext/server.py", line 76, in terminate
    psutil.Process(self.pid).terminate()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/psutil/__init__.py", line 317, in __init__
    self._init(pid)
  File "/home/innodems-intern2/snap/code/193/.local/share/pipx/venvs/pretext/lib/python3.12/site-packages/psutil/__init__.py", line 363, in _init
    raise NoSuchProcess(pid, msg=msg) from None
psutil.NoSuchProcess: process PID not found (pid=39985)
ERROR   : View encountered an error.  Please report this: process 17583 with laddr 
INFO    : Found server at localhost:8128
INFO    : Added server entry 65a4c1cc92 17583 8128 localhost

INFO    : Starting the server
INFO    : Server will soon be available at http://localhost:8128
INFO    : Opening browser for target `web` at http://localhost:8128/output/web
INFO    : Stopping server.
INFO    : 
----------------------------------------------------
INFO    : While running pretext, the following errors occurred:

INFO    : (see log messages above or in the 'logs' folder for more information)
INFO    : ----------------------------------------------------
